// Append the content hash of a public asset to its URL, so a changed file is a
// changed URL and no browser can serve a stale copy from its own cache.
//
// Pure data lookup on purpose. The map is generated by
// scripts/gen-asset-versions.mjs before every build, so this file imports JSON
// and nothing else, and is safe in a prerendered page and in the Worker alike.
// An unknown path returns unchanged rather than throwing: a missing hash
// should cost a cache-bust, never a page.
import versions from '../asset-versions.json'

export function v(path: string): string {
  const hash = (versions as Record<string, string>)[path]
  return hash ? `${path}?v=${hash}` : path
}
